#!/usr/bin/env python3
"""Generate tour meeting scenarios via LLM from a text instruction.

Usage (via make):
    make gen-meetings INSTRUCTION="3 people touring Kyoto" GEN_MODEL=openai/gpt-4o-mini
    make gen-meetings INSTRUCTION="Barcelona food tour" GEN_MODEL=openai/gpt-4o-mini NUM_MEETINGS=5 NUM_PARTICIPANTS=4
    make gen-meetings INSTRUCTION="Tokyo tour" GEN_MODEL=openai/gpt-4o-mini OUTPUT=configs.json

Usage (direct):
    python -m tour_meeting.generate_meetings "3 people touring Kyoto" --gen-model openai/gpt-4o-mini
    python -m tour_meeting.generate_meetings "Barcelona tour" --gen-model openai/gpt-4o-mini -n 5 -p 4
    python -m tour_meeting.generate_meetings "NYC tour" --gen-model openai/gpt-4o-mini -o configs.json
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from typing import Any, Dict, List, Literal

from pydantic import BaseModel, Field, ValidationError

from .llm import build_litellm_kwargs, extract_json, get_format_instructions, load_llm

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Pydantic models for strict LLM output validation
# ---------------------------------------------------------------------------


class GeneratedParticipant(BaseModel):
    """A single participant generated by the LLM."""
    name: str = Field(description="Participant's name.")
    background: str = Field(description="Relevant context, experience, or situation.")
    personality: str = Field(description="Stable traits, e.g. cautious, curious, analytical, sociable.")
    preferences: str = Field(description="Likes, dislikes, priorities, and constraints.")
    personal_goals: str = Field(description="Specific goals/preferences for the tour.")
    role: Literal["facilitator", "attendee"] = Field(
        description="Role in the meeting: 'facilitator' or 'attendee'."
    )
    speaking_style: str = Field(description="Tone style (e.g. 'friendly', 'enthusiastic').")
    explanation_style: Literal["auto", "subjective", "contrastive", "both"] = Field(
        description="Explanation style: one of 'auto', 'subjective', 'contrastive', 'both'."
    )


class GeneratedMeeting(BaseModel):
    """Complete meeting scenario generated by the LLM."""
    title: str = Field(description="Meeting title.")
    global_goal: str = Field(description="Meeting objective including city name.")
    participants: list[GeneratedParticipant] = Field(
        description="List of participants for the meeting."
    )


class SupplementParticipants(BaseModel):
    """Supplementary participants generated to fill the gap."""
    participants: list[GeneratedParticipant] = Field(
        description="Additional participants to add."
    )


# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are a tour meeting scenario generator.

Requirements:
1. Create a compelling meeting title
2. Define an abstract global goal for planning a ONE-DAY tour in a city
   - Always include the city name in the global goal
3. Create exactly {num_participants} participants. No more, no less.
4. Each participant should have:
   - name
   - background (relevant context, experience, or situation)
   - personality (stable traits, e.g. cautious, curious, analytical, sociable)
   - preferences (likes, dislikes, priorities, and constraints)
   - personal_goals (specific goals/preferences for the tour)
   - role: "facilitator" or "attendee" (at most ONE facilitator per meeting)
   - speaking_style (e.g. "friendly", "enthusiastic", "analytical", "supportive")
   - explanation_style: one of ["auto", "subjective", "contrastive", "both"]
5. Preference composition across participants:
{alignment_block}

Generate varied and creative scenarios."""

# Instruction blocks controlling how participants' preferences relate to each
# other. Keys are the CLI-facing alignment levels.
_ALIGNMENT_BLOCKS: Dict[str, str] = {
    "aligned": """\
   - All participants share the same overall interests and priorities.
   - Their preferences and personal goals point in the same direction and are mutually compatible; they differ only in nuance or emphasis (e.g. all are history lovers with slightly different favorite eras).
   - Avoid introducing competing priorities or constraints.
   - Even so, keep each participant's personal_goals CONCRETE: name specific place types, activities, or experiences they want (e.g. "visit a Zen temple garden", "try a traditional tea house"), not vague wishes like "have a pleasant day".""",

    "mixed": """\
   - Participants' preferences partially overlap: some interests are shared, others are individual and differ, but they can plausibly coexist within a single day with some negotiation over time and ordering.
   - Make each participant's preferences distinct.
   - Keep each participant's personal_goals CONCRETE: name specific place types, activities, or experiences they want (e.g. "visit a Zen temple garden", "try a traditional tea house"), not vague wishes like "have a pleasant day".""",

    "conflicting": """\
   - Participants' preferences and personal goals must genuinely CONFLICT: include mutually exclusive priorities that CANNOT all be satisfied in a single day, so that satisfying one participant's top priority forces a real sacrifice from another.
   - Use concrete tensions, e.g.: slow immersive pace vs. packed itinerary; quiet cultural sites vs. lively crowded areas; strict low budget vs. upscale experiences; early-morning start vs. late-night focus; staying in one district vs. covering the whole city.
   - Do NOT make the conflicts trivially resolvable, and do NOT resolve them yourself; the discussion is where trade-offs get negotiated.
   - Keep each participant's personal_goals CONCRETE: name specific place types, activities, or experiences they want (e.g. "visit a Zen temple garden", "try a traditional tea house"), not vague wishes like "have a pleasant day".""",
}

_USER_PROMPT = """\
{context_block}\
# User instructions: {instruction}

# Output Format
{format_instructions}"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _truncate_for_retry_context(text: str, max_len: int = 3000) -> str:
    """Truncate text for inclusion in retry error context."""
    value = (text or "").strip()
    if len(value) <= max_len:
        return value
    return value[: max_len - 3].rstrip() + "..."


def _enforce_facilitator_limit(participants: List[Dict[str, Any]]) -> None:
    """Ensure at most one facilitator exists (mutates in place).

    If multiple facilitators are found, only the first one keeps the role.
    """
    found = False
    for p in participants:
        if p["role"] == "facilitator":
            if found:
                p["role"] = "attendee"
            else:
                found = True


def _llm_call(llm_kwargs: dict, messages: list[dict[str, str]]) -> str:
    """Single litellm.completion call, returns content string."""
    import litellm as _litellm
    resp = _litellm.completion(messages=messages, **llm_kwargs)
    return resp.choices[0].message.content or ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_meeting(
    instruction: str,
    model_name: str,
    num_participants: int = 3,
    context: str = "",
    temperature: float = 1.0,
    seed: int | None = None,
    max_retries: int = 5,
    alignment: str = "mixed",
) -> Dict[str, Any]:
    """Generate meeting config (title, global_goals, participants) via LLM.

    Uses Pydantic models for strict validation and a message-chain retry loop.
    On JSON parse or validation failure, the error is fed back to the LLM.
    On participant count mismatch (too few), a supplement request is appended
    to the conversation and the LLM is asked to generate the missing participants.

    Raises RuntimeError if all retries are exhausted.

    Args:
        instruction: User instruction for the scenario.
        model_name: LLM to use for generation.
        num_participants: Exact number of participants to generate.
        context: Optional context from previously generated meetings.
        temperature: Sampling temperature for the generation LLM.
        seed: Random seed for the generation LLM.
        max_retries: Max retry attempts for the entire generation.
        alignment: How participants' preferences relate to each other:
            "aligned" (same direction), "mixed" (partial overlap), or
            "conflicting" (mutually exclusive priorities).

    Returns:
        Dict with keys: title, global_goals, participants.
    """
    if alignment not in _ALIGNMENT_BLOCKS:
        raise ValueError(
            f"Invalid alignment {alignment!r}, must be one of {sorted(_ALIGNMENT_BLOCKS)}"
        )

    # 1. Load LLM for generation
    llm = load_llm(model_name=model_name, temperature=temperature, seed=seed)
    llm_kwargs = build_litellm_kwargs(llm)

    # 2. Build system prompt
    system_prompt = _SYSTEM_PROMPT.format(
        num_participants=num_participants,
        alignment_block=_ALIGNMENT_BLOCKS[alignment],
    )

    # 3. Build user message
    context_block = ""
    if context:
        context_block = (
            "# Previously generated meetings (generate a DIFFERENT scenario from these):\n"
            + context + "\n\n"
        )
    user_message = _USER_PROMPT.format(
        context_block=context_block,
        instruction=instruction or "None (generate freely)",
        format_instructions=get_format_instructions(GeneratedMeeting),
    )

    logger.info("Generating meeting config with %s (target: %d participants) ...",
                model_name, num_participants)

    # 4. Retry loop with message chain
    #    - `messages`: clean conversation history (only successful exchanges)
    #    - `error_context`: temporary error feedback (cleared on success)
    messages: list[dict[str, str]] = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]
    error_context: list[dict[str, str]] = []
    pending_meeting: GeneratedMeeting | None = None
    pending_participants: List[Dict[str, Any]] = []
    last_error: Exception | None = None

    for attempt in range(max_retries):
        content = _llm_call(llm_kwargs, messages + error_context)

        if pending_meeting is not None:
            # --- Supplement mode: parse additional participants ---
            try:
                data = extract_json(content)
            except (ValueError, json.JSONDecodeError) as exc:
                last_error = exc
                error_context.append({"role": "assistant", "content": _truncate_for_retry_context(content)})
                error_context.append({"role": "user", "content":
                    f"Could not parse your response as JSON. Error: {exc}\n"
                    "Please respond with a valid JSON object containing a \"participants\" array."
                })
                logger.warning("Supplement JSON parse failed (attempt %d/%d): %s",
                               attempt + 1, max_retries, exc)
                continue

            try:
                supplement = SupplementParticipants(**data)
            except ValidationError as exc:
                last_error = exc
                error_context.append({"role": "assistant", "content": _truncate_for_retry_context(content)})
                error_context.append({"role": "user", "content":
                    f"Validation error in supplement response: {exc}\n"
                    "Please fix the JSON and try again."
                })
                logger.warning("Supplement validation failed (attempt %d/%d): %s",
                               attempt + 1, max_retries, exc)
                continue

            # Supplement parsed successfully — clear error context
            error_context.clear()

            # Add supplement participants
            for p in supplement.participants:
                if len(pending_participants) >= num_participants:
                    break
                pending_participants.append(p.model_dump())

            # Still not enough?
            if len(pending_participants) < num_participants:
                needed = num_participants - len(pending_participants)
                messages.append({"role": "assistant", "content": content})
                messages.append({"role": "user", "content":
                    f"Thanks, but we still need {needed} more participant(s) "
                    f"(currently have {len(pending_participants)}/{num_participants}). "
                    f"Generate exactly {needed} more participant(s) with role \"attendee\".\n\n"
                    + get_format_instructions(SupplementParticipants)
                })
                logger.info("Still need %d more participants (attempt %d/%d)",
                            needed, attempt + 1, max_retries)
                continue

            # Enough — finalize
            _enforce_facilitator_limit(pending_participants)
            return {
                "title": pending_meeting.title,
                "global_goals": pending_meeting.global_goal,
                "participants": pending_participants,
            }

        else:
            # --- Initial mode: parse full meeting ---
            try:
                data = extract_json(content)
            except (ValueError, json.JSONDecodeError) as exc:
                last_error = exc
                error_context.append({"role": "assistant", "content": _truncate_for_retry_context(content)})
                error_context.append({"role": "user", "content":
                    f"Could not parse your response as JSON. Error: {exc}\n"
                    "Please respond with a valid JSON object matching the required schema."
                })
                logger.warning("JSON parse failed (attempt %d/%d): %s",
                               attempt + 1, max_retries, exc)
                continue

            try:
                meeting = GeneratedMeeting(**data)
            except ValidationError as exc:
                last_error = exc
                error_context.append({"role": "assistant", "content": _truncate_for_retry_context(content)})
                error_context.append({"role": "user", "content":
                    f"Validation error: {exc}\n"
                    "Please fix the JSON and respond again with a valid object."
                })
                logger.warning("Validation failed (attempt %d/%d): %s",
                               attempt + 1, max_retries, exc)
                continue

            # Parsed successfully — clear error context
            error_context.clear()

            participants = [p.model_dump() for p in meeting.participants]

            # Too many → truncate
            if len(participants) > num_participants:
                logger.info("Got %d participants, truncating to %d",
                            len(participants), num_participants)
                participants = participants[:num_participants]

            # Too few → enter supplement mode
            if len(participants) < num_participants:
                needed = num_participants - len(participants)
                pending_meeting = meeting
                pending_participants = participants
                messages.append({"role": "assistant", "content": content})
                messages.append({"role": "user", "content":
                    f"You generated {len(participants)} participants but "
                    f"{num_participants} are needed. "
                    f"Generate exactly {needed} more participant(s) with role \"attendee\".\n\n"
                    + get_format_instructions(SupplementParticipants)
                })
                logger.info("Got %d participants, requesting %d more (attempt %d/%d)",
                            len(participants), needed, attempt + 1, max_retries)
                continue

            # Exact count — success
            _enforce_facilitator_limit(participants)
            return {
                "title": meeting.title,
                "global_goals": meeting.global_goal,
                "participants": participants,
            }

    raise RuntimeError(
        f"Failed to generate meeting after {max_retries} attempts. "
        f"Last error: {last_error}"
    )


def generate_meetings(
    instruction: str,
    model_name: str,
    num_meetings: int = 1,
    num_participants: int = 3,
    temperature: float = 1.0,
    seed: int | None = None,
    max_retries: int = 5,
    max_total_attempts: int | None = None,
    on_meeting: Any | None = None,
    alignment: str = "mixed",
) -> List[Dict[str, Any]]:
    """Generate multiple meeting configs, discarding failures.

    Uses a while loop that accumulates valid meetings until num_meetings
    are collected. If a single meeting generation fails after all retries,
    it is discarded and a new attempt is made.

    Args:
        instruction: User instruction for the scenario.
        model_name: LLM to use for generation.
        num_meetings: Number of meetings to generate.
        num_participants: Exact number of participants per meeting.
        temperature: Sampling temperature for the generation LLM.
        seed: Random seed for the generation LLM.
        max_retries: Max retry attempts per meeting generation.
        max_total_attempts: Max total attempts to prevent infinite loop
            (defaults to num_meetings * 2).
        on_meeting: Optional callback called after each successful meeting.
            Receives the current results list.
        alignment: How participants' preferences relate to each other
            ("aligned", "mixed", or "conflicting"); see generate_meeting.

    Returns:
        List of dicts, each with keys: title, global_goals, participants.
    """
    if max_total_attempts is None:
        max_total_attempts = num_meetings * 2

    results: List[Dict[str, Any]] = []
    context_parts: List[str] = []
    total_attempts = 0

    while len(results) < num_meetings and total_attempts < max_total_attempts:
        total_attempts += 1
        meeting_num = len(results) + 1
        logger.info("Generating meeting %d/%d (attempt %d/%d) ...",
                     meeting_num, num_meetings, total_attempts, max_total_attempts)
        context = "\n".join(context_parts) if context_parts else ""

        try:
            config = generate_meeting(
                instruction=instruction,
                model_name=model_name,
                num_participants=num_participants,
                context=context,
                temperature=temperature,
                seed=seed,
                max_retries=max_retries,
                alignment=alignment,
            )
        except Exception as exc:
            logger.warning(
                "Meeting generation failed after all retries (attempt %d/%d): %s. "
                "Discarding and trying again.",
                total_attempts, max_total_attempts, exc,
            )
            continue

        results.append(config)

        if on_meeting is not None:
            on_meeting(results)

        # Build context summary for next iteration (only successful meetings)
        names = ", ".join(p["name"] for p in config["participants"])
        context_parts.append(
            f"- Meeting {meeting_num}: \"{config['title']}\" "
            f"({config['global_goals']}) — Participants: {names}"
        )

    if len(results) < num_meetings:
        logger.error(
            "Could only generate %d/%d meetings after %d total attempts.",
            len(results), num_meetings, max_total_attempts,
        )

    return results


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate tour meeting scenarios via LLM",
    )
    parser.add_argument(
        "instruction",
        help="Instruction for meeting generation (e.g. '3 people touring Kyoto, focus on temples and food')",
    )
    parser.add_argument(
        "--gen-model",
        required=True,
        help="LLM to use for generation (e.g. openai/gpt-4o-mini, vllm/0/Qwen/Qwen3-8B)",
    )
    parser.add_argument(
        "--num-meetings", "-n",
        type=int,
        default=1,
        help="Number of meetings to generate (default: 1)",
    )
    parser.add_argument(
        "--num-participants", "-p",
        type=int,
        default=3,
        help="Number of participants per meeting (default: 3)",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Save generated config(s) to a JSON file",
    )
    parser.add_argument(
        "--temperature", "-t",
        type=float,
        default=1.0,
        help="Sampling temperature for the generation LLM (default: 1.0)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for the generation LLM (default: None)",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=5,
        help="Max retries per meeting generation (default: 5)",
    )
    parser.add_argument(
        "--max-total-attempts",
        type=int,
        default=None,
        help="Max total attempts across all meetings (default: num_meetings * 3)",
    )
    parser.add_argument(
        "--alignment",
        choices=sorted(_ALIGNMENT_BLOCKS),
        default="mixed",
        help="How participants' preferences relate: aligned (same direction), "
             "mixed (partial overlap, default), conflicting (mutually exclusive priorities)",
    )
    args = parser.parse_args()

    # Generate
    print(f"[+] Generating {args.num_meetings} meeting(s) "
          f"with {args.num_participants} participants each "
          f"using {args.gen_model} ...", file=sys.stderr)

    def _on_meeting(results: List[Dict[str, Any]]) -> None:
        config = results[-1]
        i = len(results)
        names = ", ".join(p["name"] for p in config["participants"])
        print(f"[+] Meeting {i}: {config['title']} "
              f"({len(config['participants'])} participants: {names})", file=sys.stderr)
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                json.dump({"meetings": results}, f, indent=2, ensure_ascii=False)
            print(f"[+] Saved to {args.output} ({i} meeting(s))", file=sys.stderr)

    configs = generate_meetings(
        instruction=args.instruction,
        model_name=args.gen_model,
        num_meetings=args.num_meetings,
        num_participants=args.num_participants,
        temperature=args.temperature,
        seed=args.seed,
        max_retries=args.max_retries,
        max_total_attempts=args.max_total_attempts,
        on_meeting=_on_meeting,
        alignment=args.alignment,
    )

    if not args.output:
        print(json.dumps({"meetings": configs}, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
