#!/usr/bin/env python3
"""Run tour meetings from a JSON file generated by gen-meetings.

Usage (via make):
    make run-meetings MEETING=kyoto_tours.json MODEL=openai/gpt-4o-mini OUTPUT=results.json
    make run-meetings MEETING=barcelona_tours.json MODEL=openai/gpt-4o-mini OUTPUT=results.json MAX_TURNS=50 INDEX=0

Usage (direct):
    python -m tour_meeting.run_meetings kyoto_tours.json --model openai/gpt-4o-mini --output results.json
    python -m tour_meeting.run_meetings barcelona_tours.json --model openai/gpt-4o-mini --output results.json --index 0
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from typing import Any, Dict, List

from .cli import build_meeting


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run meetings from a JSON file generated by gen-meetings"
    )
    parser.add_argument(
        "input",
        help="JSON file generated by gen-meetings",
    )
    parser.add_argument(
        "--model",
        required=True,
        nargs="+",
        help="LLM(s) that instantiate participants. Multiple values are "
             "assigned to participants in order and cycled if fewer than "
             "participants (e.g. --model openai/gpt-4o-mini anthropic/claude-sonnet-5)",
    )
    parser.add_argument(
        "--max-turns",
        type=int,
        default=100,
        help="Maximum number of turns per meeting (default: 100)",
    )
    parser.add_argument(
        "--turn-rule",
        default="round_robin",
        help="Turn rule for the conversation phase (default: round_robin)",
    )
    parser.add_argument(
        "--voting-rule",
        default="majority",
        help="Voting rule for the voting phase (default: majority)",
    )
    parser.add_argument(
        "--vote-turn-rule",
        default=None,
        help="Turn rule for the voting phase (default: round_robin)",
    )
    parser.add_argument(
        "--time-limit",
        type=int,
        default=None,
        help="Time limit per meeting in seconds (default: unlimited)",
    )
    parser.add_argument(
        "--volunteer-mode",
        choices=["true", "false"],
        default=None,
        help="Allow participants to skip their own turn (default: false)",
    )
    parser.add_argument(
        "--balanced-turns",
        choices=["true", "false"],
        default=None,
        help="Balance speaking turns across participants (default: true)",
    )
    parser.add_argument(
        "--enable-post-eval",
        choices=["true", "false"],
        default=None,
        help="Run the participants' self-evaluation at the end of each meeting "
             "when consensus is reached (default: true)",
    )
    parser.add_argument(
        "--single-decider",
        default=None,
        help="0-based index or 'facilitator': the participant who acts as the "
             "designated decider in each meeting (used with --voting-rule "
             "single_decider). 'facilitator' picks the participant with the "
             "facilitator role, falling back to index 0 if there is none.",
    )
    parser.add_argument(
        "--travel-date",
        default=None,
        help="Constraint: travel date (e.g. 2026-08-01)",
    )
    parser.add_argument(
        "--time-window-start",
        default=None,
        help="Constraint: tour start time (e.g. 09:00)",
    )
    parser.add_argument(
        "--time-window-end",
        default=None,
        help="Constraint: tour end time (e.g. 18:00)",
    )
    parser.add_argument(
        "--budget",
        default=None,
        help="Constraint: budget per participant (e.g. '$600')",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        nargs="+",
        default=[0.7],
        help="Sampling temperature(s) for participant LLMs, assigned to "
             "participants in order and cycled (default: 0.7)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        nargs="+",
        default=[42],
        help="Random seed(s) for participant LLMs, assigned to "
             "participants in order and cycled (default: 42)",
    )
    parser.add_argument(
        "--index",
        type=int,
        default=None,
        help="Run only the meeting at this index (0-based; default: run all)",
    )
    parser.add_argument(
        "--output", "-o",
        required=True,
        help="JSON file to save analytics of all meetings to",
    )
    args = parser.parse_args()

    single_decider_index = None
    if args.single_decider is not None and args.single_decider != "facilitator":
        try:
            single_decider_index = int(args.single_decider)
        except ValueError:
            print(f"[!] --single-decider must be a 0-based index or 'facilitator', "
                  f"got '{args.single_decider}'", file=sys.stderr)
            sys.exit(1)

    # Confirm before overwriting an existing output file
    if os.path.exists(args.output):
        if sys.stdin.isatty():
            answer = input(f"[?] Output file '{args.output}' already exists. Overwrite? [y/N]: ")
            if answer.strip().lower() not in ("y", "yes"):
                print("[!] Aborted.", file=sys.stderr)
                sys.exit(1)
        else:
            print(f"[!] Output file '{args.output}' already exists. "
                  "Refusing to overwrite in non-interactive mode. "
                  "Choose a different OUTPUT file or remove the existing one.", file=sys.stderr)
            sys.exit(1)

    try:
        with open(args.input, encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"[!] Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"[!] Failed to parse {args.input}: {e}", file=sys.stderr)
        sys.exit(1)

    meetings: List[Dict[str, Any]] = data.get("meetings", [])
    if not meetings:
        print(f"[!] No meetings found in {args.input}", file=sys.stderr)
        sys.exit(1)

    if args.index is not None:
        if not 0 <= args.index < len(meetings):
            print(
                f"[!] Index {args.index} is out of range "
                f"({args.input} contains {len(meetings)} meeting(s))",
                file=sys.stderr,
            )
            sys.exit(1)
        selected = [(args.index, meetings[args.index])]
    else:
        selected = list(enumerate(meetings))

    settings: Dict[str, Any] = {
        "max_turns": args.max_turns,
        "turn_rule": args.turn_rule,
        "voting_rule": args.voting_rule,
    }
    if args.vote_turn_rule is not None:
        settings["vote_turn_rule"] = args.vote_turn_rule
    if args.time_limit is not None:
        settings["time_limit"] = args.time_limit
    if args.volunteer_mode is not None:
        settings["volunteer_mode"] = args.volunteer_mode == "true"
    if args.balanced_turns is not None:
        settings["balanced_turns"] = args.balanced_turns == "true"
    if args.enable_post_eval is not None:
        settings["enable_post_eval"] = args.enable_post_eval == "true"

    cli_constraints = {
        key: value
        for key, value in {
            "travel_date": args.travel_date,
            "time_window_start": args.time_window_start,
            "time_window_end": args.time_window_end,
            "budget": args.budget,
        }.items()
        if value is not None
    }

    analytics_results: List[Dict[str, Any]] = []

    print(f"[+] Running {len(selected)} meeting(s) from {args.input} "
          f"using {', '.join(args.model)} ...", file=sys.stderr)

    for i, config in selected:
        participants = [
            {
                **cfg,
                "model_name": args.model[j % len(args.model)],
                "temperature": args.temperature[j % len(args.temperature)],
                "seed": args.seed[j % len(args.seed)],
            }
            for j, cfg in enumerate(config["participants"])
        ]
        meeting_settings = dict(settings)
        if args.single_decider == "facilitator":
            decider = next(
                (p for p in config["participants"] if p.get("role") == "facilitator"),
                config["participants"][0],
            )
            meeting_settings["single_decider"] = decider["name"]
        elif single_decider_index is not None:
            if not 0 <= single_decider_index < len(config["participants"]):
                print(
                    f"[!] --single-decider {single_decider_index} is out of range "
                    f"(meeting {i} has {len(config['participants'])} participants)",
                    file=sys.stderr,
                )
                sys.exit(1)
            meeting_settings["single_decider"] = config["participants"][single_decider_index]["name"]

        constraints = {**(config.get("constraints") or {}), **cli_constraints} or None
        meeting = build_meeting(
            title=config["title"],
            global_goals=config["global_goals"],
            participants=participants,
            constraints=constraints,
            settings=meeting_settings,
        )

        print(f"\n[+] ===== Meeting {i}: {config['title']} =====\n", file=sys.stderr)
        asyncio.run(meeting.run_cli())

        analytics_results.append({
            "index": i,
            "title": config["title"],
            "participants": [
                {
                    "name": p["name"],
                    "model_name": p["model_name"],
                    "temperature": p["temperature"],
                    "seed": p["seed"],
                }
                for p in participants
            ],
            "analytics": meeting.export_analytics(),
        })
        with open(args.output, "w", encoding="utf-8") as f:
            json.dump({"meetings": analytics_results}, f, indent=2, ensure_ascii=False)
        print(f"[+] Saved analytics to {args.output} ({len(analytics_results)} meeting(s))", file=sys.stderr)


if __name__ == "__main__":
    main()
