FROM node:24-alpine

WORKDIR /app

COPY ../tour_meeting/frontend/package*.json ./
COPY ../tour_meeting/frontend/.npmrc ./
RUN npm install

COPY ../tour_meeting/frontend .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
